# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'latest_garvis3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvis_gui(object):
    def setupUi(self, jarvis_gui):
        jarvis_gui.setObjectName("jarvis_gui")
        jarvis_gui.resize(1331, 723)
        self.centralwidget = QtWidgets.QWidget(jarvis_gui)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_0 = QtWidgets.QLabel(self.centralwidget)
        self.bg_0.setGeometry(QtCore.QRect(-130, 0, 1461, 781))
        self.bg_0.setText("")
        self.bg_0.setPixmap(QtGui.QPixmap(".\\design\\BG\\Black_Template.jpg"))
        self.bg_0.setScaledContents(True)
        self.bg_0.setObjectName("bg_0")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(10, 10, 501, 331))
        self.bg_1.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                "background-color: rgb(16, 178, 214);")
        self.bg_1.setText("")
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(530, 10, 501, 331))
        self.bg_2.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                "background-color: rgb(16, 178, 214);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(20, 20, 481, 311))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap(".\\design\\BG\\Iron_Template_1.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(540, 20, 481, 311))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap(".\\design\\extra gui\\live.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(-170, 210, 681, 521))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap(".\\design\\extra gui\\__1.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(1040, 10, 281, 181))
        self.bg_3.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                "background-color: rgb(16, 178, 214);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(1050, 20, 261, 161))
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap(".\\design\\extra gui\\Earth_Template.gif"))
        self.gif_4.setScaledContents(True)
        self.gif_4.setObjectName("gif_4")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(460, 360, 471, 231))
        self.bg_4.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                "background-color: rgb(16, 178, 214);")
        self.bg_4.setText("")
        self.bg_4.setObjectName("bg_4")
        self.gif_5 = QtWidgets.QLabel(self.centralwidget)
        self.gif_5.setGeometry(QtCore.QRect(470, 370, 451, 211))
        self.gif_5.setText("")
        self.gif_5.setPixmap(QtGui.QPixmap(".\\design\\extra gui\\initial.gif"))
        self.gif_5.setScaledContents(True)
        self.gif_5.setObjectName("gif_5")
        self.bg_startbutton = QtWidgets.QLabel(self.centralwidget)
        self.bg_startbutton.setGeometry(QtCore.QRect(530, 620, 211, 61))
        self.bg_startbutton.setText("")
        self.bg_startbutton.setPixmap(QtGui.QPixmap(".\\design\\Buttons\\Start.png"))
        self.bg_startbutton.setScaledContents(True)
        self.bg_startbutton.setObjectName("bg_startbutton")
        self.bg_quitbutton = QtWidgets.QLabel(self.centralwidget)
        self.bg_quitbutton.setGeometry(QtCore.QRect(760, 630, 211, 51))
        self.bg_quitbutton.setText("")
        self.bg_quitbutton.setPixmap(QtGui.QPixmap(".\\design\\Buttons\\Quit.png"))
        self.bg_quitbutton.setScaledContents(True)
        self.bg_quitbutton.setObjectName("bg_quitbutton")
        self.Start_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Start_pushbutton.setGeometry(QtCore.QRect(520, 620, 221, 61))
        self.Start_pushbutton.setStyleSheet("background-color: Transparent;\n"
                                            "border-raius:none;")
        self.Start_pushbutton.setText("")
        self.Start_pushbutton.setObjectName("Start_pushbutton")
        self.Quit_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Quit_pushbutton.setGeometry(QtCore.QRect(760, 620, 221, 61))
        self.Quit_pushbutton.setStyleSheet("background-color: Transparent;\n"
                                           "border-raius:none;")
        self.Quit_pushbutton.setText("")
        self.Quit_pushbutton.setObjectName("Quit_pushbutton")
        self.text_background = QtWidgets.QLabel(self.centralwidget)
        self.text_background.setGeometry(QtCore.QRect(990, 390, 231, 81))
        self.text_background.setText("")
        self.text_background.setPixmap(QtGui.QPixmap(".\\design\\BG\\back.jpg"))
        self.text_background.setScaledContents(True)
        self.text_background.setObjectName("text_background")
        self.text_background_2 = QtWidgets.QLabel(self.centralwidget)
        self.text_background_2.setGeometry(QtCore.QRect(990, 480, 231, 81))
        self.text_background_2.setText("")
        self.text_background_2.setPixmap(QtGui.QPixmap(".\\design\\BG\\back.jpg"))
        self.text_background_2.setScaledContents(True)
        self.text_background_2.setObjectName("text_background_2")
        self.dis_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.dis_time.setGeometry(QtCore.QRect(1010, 410, 201, 51))
        self.dis_time.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "font: 75 22pt \"MS Shell Dlg 2\";\n"
                                    "background-color: Transparent;\n"
                                    "border-radius:none;")
        self.dis_time.setObjectName("dis_time")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(1040, 200, 281, 161))
        self.bg_5.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                "background-color: rgb(16, 178, 214);")
        self.bg_5.setText("")
        self.bg_5.setPixmap(QtGui.QPixmap(".\\design\\BG\\Black_Template.jpg"))
        self.bg_5.setScaledContents(True)
        self.bg_5.setObjectName("bg_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1050, 210, 251, 131))
        self.textBrowser.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                       "background-color: Transparent;\n"
                                       "border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.dis_date = QtWidgets.QTextBrowser(self.centralwidget)
        self.dis_date.setGeometry(QtCore.QRect(1010, 500, 201, 51))
        self.dis_date.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "font: 75 22pt \"MS Shell Dlg 2\";\n"
                                    "background-color: Transparent;\n"
                                    "border-radius:none;")
        self.dis_date.setObjectName("dis_date")
        self.bg_0.raise_()
        self.bg_2.raise_()
        self.gif_2.raise_()
        self.gif_3.raise_()
        self.bg_1.raise_()
        self.gif_1.raise_()
        self.bg_3.raise_()
        self.gif_4.raise_()
        self.bg_4.raise_()
        self.gif_5.raise_()
        self.bg_startbutton.raise_()
        self.bg_quitbutton.raise_()
        self.Start_pushbutton.raise_()
        self.Quit_pushbutton.raise_()
        self.text_background.raise_()
        self.text_background_2.raise_()
        self.dis_time.raise_()
        self.bg_5.raise_()
        self.textBrowser.raise_()
        self.dis_date.raise_()
        jarvis_gui.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvis_gui)
        QtCore.QMetaObject.connectSlotsByName(jarvis_gui)

    def retranslateUi(self, jarvis_gui):
        _translate = QtCore.QCoreApplication.translate
        jarvis_gui.setWindowTitle(_translate("jarvis_gui", "MainWindow"))
        self.dis_time.setHtml(_translate("jarvis_gui",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:22pt; font-weight:72; font-style:normal;\">\n"
                                         "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dis_date.setHtml(_translate("jarvis_gui",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:22pt; font-weight:72; font-style:normal;\">\n"
                                         "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


# if __name__ == "__main__":
#     import sys
#
#     app = QtWidgets.QApplication(sys.argv)
#     jarvis_gui = QtWidgets.QMainWindow()
#     ui = Ui_jarvis_gui()
#     ui.setupUi(jarvis_gui)
#     jarvis_gui.show()
#     sys.exit(app.exec_())
